#!/system/bin/sh
# Thanks to:
# hellsgod, malaroth, osm0sis, joaquinf, The Gingerbread Man, pkgnex, Khrushy, shreddintyres

# disable sysctl.conf to prevent ROM interference
if [ -e /system/etc/sysctl.conf ]; then
  mount -o remount,rw /system;
  mv /system/etc/sysctl.conf /system/etc/sysctl.conf.fkbak;
  mount -o remount,ro /system;
fi;

# wait for systemui, increase its priority and make it unkillable
while sleep 1; do
  if [ `pidof com.android.systemui` ]; then
    systemui=`$bb pidof com.android.systemui`;
    busybox renice -18 $systemui;
    echo -17 > /proc/$systemui/oom_adj;
    chmod 100 /proc/$systemui/oom_adj;
    exit;
  fi;
done&
 
# lmk whitelist for common launchers and increase launcher priority
list="com.android.launcher org.adw.launcher org.adwfreak.launcher net.alamoapps.launcher com.anddoes.launcher com.android.lmt com.chrislacy.actionlauncher.pro com.cyanogenmod.trebuchet com.gau.go.launcherex com.gtp.nextlauncher com.miui.mihome2 com.mobint.hololauncher com.mobint.hololauncher.hd com.qihoo360.launcher com.teslacoilsw.launcher com.tsf.shell org.zeam";
while sleep 60; do
  for class in $list; do
    if [ `pgrep $class` ]; then
      launcher=`$bb pgrep $class`;
      echo -17 > /proc/$launcher/oom_adj;
      chmod 100 /proc/$launcher/oom_adj;
      busybox renice -18 $launcher;
    fi;
  done;
  exit;
done&

# enable gpu conservative governor
#echo "conservative" > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/pwrscale/policy

# enable wheatley io_is_busy
#echo "1" > /sys/devices/system/cpu/cpufreq/wheatley/io_is_busy

