#!/system/bin/sh
#
# AK
#

# set freqs clock at boot
min=384000
max=1512000
echo "$min" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo "$min" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
echo "$min" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
echo "$min" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq
echo "$max" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "$max" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
echo "$max" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
echo "$max" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq

# set conservative gpu policy 
echo "conservative" > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/pwrscale/policy
