#!/system/bin/sh
# Thanks to:
# hellsgod, malaroth, osm0sis, joaquinf, The Gingerbread Man, pkgnex, Khrushy, shreddintyres

# wait for systemui, increase its priority and make it unkillable
while sleep 1; do
  if [ `pidof com.android.systemui` ]; then
    systemui=`$bb pidof com.android.systemui`;
    busybox renice -18 $systemui;
    echo -17 > /proc/$systemui/oom_adj;
    chmod 100 /proc/$systemui/oom_adj;
    exit;
  fi;
done&
 
# lmk whitelist for common launchers and increase launcher priority
list="com.android.launcher org.adw.launcher org.adwfreak.launcher net.alamoapps.launcher com.anddoes.launcher com.android.lmt com.chrislacy.actionlauncher.pro com.cyanogenmod.trebuchet com.gau.go.launcherex com.gtp.nextlauncher com.miui.mihome2 com.mobint.hololauncher com.mobint.hololauncher.hd com.qihoo360.launcher com.teslacoilsw.launcher com.tsf.shell org.zeam";
while sleep 60; do
  for class in $list; do
    if [ `pgrep $class` ]; then
      launcher=`$bb pgrep $class`;
      echo -17 > /proc/$launcher/oom_adj;
      chmod 100 /proc/$launcher/oom_adj;
      busybox renice -18 $launcher;
    fi;
  done;
  exit;
done&

# remount ext4 with some optimizations
found=$(cat /proc/version | grep AK);
if [ "$found" != "" ]; then
  #########################
  # Tweak mount partition
  #########################
  found=$(mount | grep ext4 | grep by-name/system);
  if [ "$found" != "" ]; then
	mount -o remount,ro,noatime,noauto_da_alloc,barrier=0 /system
  fi

  found=$(mount | grep ext4 | grep by-name/userdata);
  if [ "$found" != "" ]; then
	mount -o remount,noatime,nosuid,nodev,nomblk_io_submit,errors=panic,noauto_da_alloc,barrier=0,commit=120,data=writeback,nobh /data
  fi

  found=$(mount | grep ext4 | grep by-name/cache);
  if [ "$found" != "" ]; then
	mount -o remount,noatime,nosuid,nodev,nomblk_io_submit,errors=panic,noauto_da_alloc,barrier=0,commit=300,data=writeback,nobh /cache
  fi

fi

# set min/max freqs at boot
fmin=384000
fmax=1512000
echo "$fmin" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo "$fmin" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
echo "$fmin" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
echo "$fmin" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq
echo "$fmax" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "$fmax" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
echo "$fmax" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
echo "$fmax" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq

# enable gpu conservative governor
#echo "conservative" > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/pwrscale/policy

# enable wheatley io_is_busy
#echo "1" > /sys/devices/system/cpu/cpufreq/wheatley/io_is_busy

