#!/system/bin/sh
# Thanks to:
# hellsgod, malaroth, osm0sis, joaquinf, The Gingerbread Man, pkgnex, Khrushy, shreddintyres

# disable sysctl.conf to prevent ROM interference
if [ -e /system/etc/sysctl.conf ]; then
  mount -o remount,rw /system;
  mv /system/etc/sysctl.conf /system/etc/sysctl.conf.fkbak;
  mount -o remount,ro /system;
fi;

# wait for systemui, increase its priority and make it unkillable
while sleep 1; do
  if [ `pidof com.android.systemui` ]; then
    systemui=`$bb pidof com.android.systemui`;
    busybox renice -18 $systemui;
    echo -17 > /proc/$systemui/oom_adj;
    chmod 100 /proc/$systemui/oom_adj;
    exit;
  fi;
done&
 
# lmk whitelist for common launchers and increase launcher priority
list="com.android.launcher org.adw.launcher org.adwfreak.launcher net.alamoapps.launcher com.anddoes.launcher com.android.lmt com.chrislacy.actionlauncher.pro com.cyanogenmod.trebuchet com.gau.go.launcherex com.gtp.nextlauncher com.miui.mihome2 com.mobint.hololauncher com.mobint.hololauncher.hd com.qihoo360.launcher com.teslacoilsw.launcher com.tsf.shell org.zeam";
while sleep 60; do
  for class in $list; do
    if [ `pgrep $class` ]; then
      launcher=`$bb pgrep $class`;
      echo -17 > /proc/$launcher/oom_adj;
      chmod 100 /proc/$launcher/oom_adj;
      busybox renice -18 $launcher;
    fi;
  done;
  exit;
done&

# vm-tweaks
echo "4096" > /proc/sys/vm/min_free_kbytes;
echo "0" > /proc/sys/vm/oom_kill_allocating_task;
echo "0" > /proc/sys/vm/panic_on_oom;
echo "0" > /proc/sys/vm/laptop_mode;
echo "0" > /proc/sys/vm/swappiness;
echo "50" > /proc/sys/vm/vfs_cache_pressure;
echo "90" > /proc/sys/vm/dirty_ratio;
echo "1" > /proc/sys/vm/overcommit_memory;
echo "4" > /proc/sys/vm/min_free_order_shift;
echo "1" > /proc/sys/vm/oom_dump_tasks;
echo "0" > /proc/sys/vm/swappiness
echo "1000" > /proc/sys/vm/dirty_writeback_centisecs;
echo "500" > /proc/sys/vm/dirty_expire_centisecs;
echo "8" > /proc/sys/vm/page-cluster;
echo "3" > /proc/sys/vm/drop_caches

# fs-tweaks
echo "10" > /proc/sys/fs/lease-break-time;
echo "32000" > /proc/sys/fs/inotify/max_queued_events;
echo "524288" > /proc/sys/fs/file-max;
echo "256" > /proc/sys/fs/inotify/max_user_instances;
echo "10240" > /proc/sys/fs/inotify/max_user_watches;

# kernel-tweaks
echo "1000000" > /proc/sys/kernel/sched_min_granularity_ns;
echo "18000000" > /proc/sys/kernel/sched_latency_ns;
echo "3000000" > /proc/sys/kernel/sched_wakeup_granularity_ns;
echo "0" > /proc/sys/kernel/panic;
echo "1" > /proc/sys/kernel/panic_on_oops;
echo "64000" > /proc/sys/kernel/msgmni;
echo "64000" > /proc/sys/kernel/msgmax;
echo "4096" > /proc/sys/kernel/shmmni;
echo "2097152" > /proc/sys/kernel/shmall;
echo "536870912" > /proc/sys/kernel/shmmax;
echo "524288" > /proc/sys/kernel/threads-max;
echo "500 512000 64 2048" > /proc/sys/kernel/sem;
echo "0" > /proc/sys/kernel/sched_child_runs_first;
